outputs:
  save_scored: true
  save_extracted: false

scored:
  include_full: true
  short_intron_length: 40 

filters:
  conv_or_nonconv: null       # null / "C" / "N"
  const_or_alt: null  # null / "const" / "alt"

stats:
  detailed: true  

structure_scoring:
  max_pairs_score_max: null # range: 1-60
  total_pairs_score_max: null # range: 1-60
